apiVersion: v1
kind: Pod
metadata:
  name: my--web--app
spec:
  containers:
    - name: my-nginx-app
      image: mhmod978/project
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
